name: linting, testing, building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install modules
        run: npm install
      - uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules

  build_prod:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Build production project
        run: npm run build:prod

  lint_ts:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Linting TypeScript
        run: npm run lint:ts

  lint_scss:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Linting CSS
        run: npm run lint:scss

  unit_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Unit testing
        run: npm run test:unit

  build_storybook:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Build storybook
        run: npm run storybook:build

  ui_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules
      - name: Screenshot testing
        run: npm run test:ui:ci